name: Examen Calidad

on: [push]

jobs:
  calidad:
    runs-on: ubuntu-latest

    steps:
    #  1. Descarga código (SIEMPRE PRIMERO)
    - name: Checkout
      uses: actions/checkout@v4

    #  2. Java
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    #  3. Ejecutar tests
    - name: Ejecutar tests
      run: mvn test




